//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos
    {
        public double n_articulo { get; set; }
        public string art_descr { get; set; }
        public Nullable<double> fopd { get; set; }
        public Nullable<double> n_cliente { get; set; }
        public Nullable<double> pre_costo { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> pre_lista1 { get; set; }
        public string fecha_prec { get; set; }
        public Nullable<double> pre_lista2 { get; set; }
        public Nullable<double> pre_lista3 { get; set; }
        public Nullable<double> stock { get; set; }
        public Nullable<double> stock_min { get; set; }
        public Nullable<double> grupo { get; set; }
        public string observac { get; set; }
        public string observac1 { get; set; }
        public Nullable<double> peso1 { get; set; }
        public Nullable<double> peso2 { get; set; }
        public Nullable<double> peso3 { get; set; }
        public Nullable<double> material1 { get; set; }
        public Nullable<double> material2 { get; set; }
        public Nullable<double> material3 { get; set; }
        public Nullable<double> marco1 { get; set; }
        public Nullable<double> marco2 { get; set; }
        public Nullable<double> marco3 { get; set; }
        public Nullable<double> espesor1 { get; set; }
        public Nullable<double> espesor2 { get; set; }
        public Nullable<double> espesor3 { get; set; }
        public Nullable<double> bocas1 { get; set; }
        public Nullable<double> bocas2 { get; set; }
        public Nullable<double> bocas3 { get; set; }
        public string matriz1 { get; set; }
        public string matriz2 { get; set; }
        public string matriz3 { get; set; }
        public string cortante1 { get; set; }
        public string cortante2 { get; set; }
        public string cortante3 { get; set; }
        public Nullable<double> ciclos1 { get; set; }
        public Nullable<double> ciclos2 { get; set; }
        public Nullable<double> ciclos3 { get; set; }
        public string color1 { get; set; }
        public string color2 { get; set; }
        public string color3 { get; set; }
        public Nullable<double> cantidad { get; set; }
        public string tamanocaja { get; set; }
        public Nullable<double> tiraje_ter { get; set; }
        public Nullable<double> tiraje_tro { get; set; }
        public string fazon { get; set; }
        public int idArticulo { get; set; }
    }
}
