//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blibox_oriEntities : DbContext
    {
        public blibox_oriEntities()
            : base("name=blibox_oriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulos> articulos { get; set; }
        public virtual DbSet<cctecli> cctecli { get; set; }
        public virtual DbSet<cctepro> cctepro { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<compraso> compraso { get; set; }
        public virtual DbSet<cortanteo> cortanteo { get; set; }
        public virtual DbSet<marcos> marcos { get; set; }
        public virtual DbSet<materialo> materialo { get; set; }
        public virtual DbSet<matprim1> matprim1 { get; set; }
        public virtual DbSet<MATRICES> MATRICES { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<proveedo> proveedo { get; set; }
        public virtual DbSet<rubroo> rubroo { get; set; }
        public virtual DbSet<vendedoro> vendedoro { get; set; }
    }
}
