//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cctecli
    {
        public Nullable<double> NRO_OPERAC { get; set; }
        public Nullable<double> N_CLIENTE { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<System.DateTime> FECHA_OPER { get; set; }
        public Nullable<double> DEB_CRED { get; set; }
        public Nullable<double> IMP_OPERAC { get; set; }
        public string OBSERVAC { get; set; }
        public int idctactecli { get; set; }
    }
}
