//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public double N_CLIENTE { get; set; }
        public string RAZON_CLI { get; set; }
        public string CONTACTO { get; set; }
        public string DOMICILIO { get; set; }
        public string LOCALIDAD { get; set; }
        public Nullable<double> PROVINCIA { get; set; }
        public string CODPOS { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<double> N_VENDEDOR { get; set; }
        public Nullable<double> COMISION { get; set; }
        public Nullable<double> N_VENDEDO2 { get; set; }
        public Nullable<double> COMISION2 { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<double> COND_IVA { get; set; }
        public Nullable<double> NRO_CUIT { get; set; }
        public Nullable<double> SALDO { get; set; }
        public string OBSERVAC { get; set; }
        public string COD_ANT { get; set; }
        public string REFERIDO { get; set; }
        public Nullable<double> N_RUBRO { get; set; }
        public Nullable<double> DIAS_FF { get; set; }
        public Nullable<double> CHEQ_FF { get; set; }
        public Nullable<double> GRUPO_MAIL { get; set; }
        public Nullable<double> LIMITE_CRE { get; set; }
        public int idCliente { get; set; }
    }
}
