//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class compraso
    {
        public double N_PROVEEDO { get; set; }
        public Nullable<System.DateTime> FECHA_COMP { get; set; }
        public Nullable<double> N_FACTURA { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<double> NETO { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> NRO_OPERAC { get; set; }
        public string OBSERVAC { get; set; }
        public int idCompras { get; set; }
    }
}
