//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cortanteo
    {
        public string N_CORTANTE { get; set; }
        public string CORT_DESCR { get; set; }
        public Nullable<double> SECTOR { get; set; }
        public Nullable<double> BOCAS { get; set; }
        public string OBSERVAC { get; set; }
        public int idCortante { get; set; }
    }
}
