//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaCteClientes
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public string observacion { get; set; }
        public Nullable<decimal> importe { get; set; }
        public int tipoMovimiento { get; set; }
        public string concepto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoMovCtaCte TipoMovCtaCte { get; set; }
    }
}
