//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaCteProveedores
    {
        public int id { get; set; }
        public int id_proveedor { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public System.DateTime fecha_movimiento { get; set; }
        public string concepto { get; set; }
        public decimal importe { get; set; }
        public int tipo_movimiento { get; set; }
        public string observaciones { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoMovCtaCte TipoMovCtaCte { get; set; }
    }
}
