//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encabezado_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encabezado_Factura()
        {
            this.Detalle_factura = new HashSet<Detalle_factura>();
        }
    
        public int Nro_factura { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_cliente { get; set; }
        public Nullable<int> ID_vendedor { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Valor_inscripto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<int> ID_condicon_venta { get; set; }
        public Nullable<int> ID_movimiento { get; set; }
        public Nullable<int> Nro_remito { get; set; }
        public Nullable<int> OrdenCompra { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string CAE { get; set; }
        public int NroComprobante { get; set; }
        public Nullable<System.DateTime> FechaVencimientoCAE { get; set; }
    
        public virtual Condicion_venta Condicion_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_factura> Detalle_factura { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
