//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcos
    {
        public Nullable<double> N_MARCO { get; set; }
        public string DESCR_MARC { get; set; }
        public Nullable<double> ANCHO { get; set; }
        public Nullable<double> LARGO { get; set; }
        public string OBSERVAC { get; set; }
        public int idMarco { get; set; }
    }
}
