//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public Nullable<double> N_PEDIDO { get; set; }
        public Nullable<double> N_ARTICULO { get; set; }
        public Nullable<double> N_CLIENTE { get; set; }
        public Nullable<double> CANT_PED { get; set; }
        public Nullable<double> CANT_ENT { get; set; }
        public Nullable<System.DateTime> FECHA_PED { get; set; }
        public Nullable<System.DateTime> FECHA_ENT { get; set; }
        public string ORDEN { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<double> MATERIAL { get; set; }
        public Nullable<double> ESPESOR { get; set; }
        public Nullable<System.DateTime> FECHA1 { get; set; }
        public Nullable<double> REMITO1 { get; set; }
        public Nullable<double> CANTIDAD1 { get; set; }
        public Nullable<System.DateTime> FECHA2 { get; set; }
        public Nullable<double> REMITO2 { get; set; }
        public Nullable<double> CANTIDAD2 { get; set; }
        public Nullable<System.DateTime> FECHA3 { get; set; }
        public Nullable<double> REMITO3 { get; set; }
        public Nullable<double> CANTIDAD3 { get; set; }
        public Nullable<double> REMITO4 { get; set; }
        public Nullable<System.DateTime> FECHA4 { get; set; }
        public Nullable<double> CANTIDAD4 { get; set; }
        public Nullable<System.DateTime> FECHA5 { get; set; }
        public Nullable<double> REMITO5 { get; set; }
        public Nullable<double> CANTIDAD5 { get; set; }
        public Nullable<System.DateTime> FECHA6 { get; set; }
        public Nullable<double> REMITO6 { get; set; }
        public Nullable<double> CANTIDAD6 { get; set; }
        public Nullable<System.DateTime> FECHA7 { get; set; }
        public Nullable<double> REMITO7 { get; set; }
        public Nullable<double> CANTIDAD7 { get; set; }
        public Nullable<System.DateTime> FECHA8 { get; set; }
        public Nullable<double> REMITO8 { get; set; }
        public Nullable<double> CANTIDAD8 { get; set; }
        public Nullable<System.DateTime> FECHA9 { get; set; }
        public Nullable<double> REMITO9 { get; set; }
        public Nullable<double> CANTIDAD9 { get; set; }
        public Nullable<System.DateTime> FECHA10 { get; set; }
        public Nullable<double> REMITO10 { get; set; }
        public Nullable<double> CANTIDAD10 { get; set; }
        public string OBSERVAC { get; set; }
        public string OBSERVAC1 { get; set; }
        public Nullable<double> OBSERVAC2 { get; set; }
        public string IMPRESION { get; set; }
        public string RESPONSABL { get; set; }
        public Nullable<double> IMPMATRIZ { get; set; }
        public Nullable<double> TIPO_CAJA { get; set; }
        public string CODART_CLI { get; set; }
        public string ARMADO { get; set; }
        public Nullable<System.DateTime> F_ARMADO { get; set; }
        public Nullable<double> FOIEP { get; set; }
        public int idPedido { get; set; }
    }
}
