//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedo
    {
        public Nullable<double> N_PROVEED { get; set; }
        public string RAZON_PRO { get; set; }
        public string CONTACTO { get; set; }
        public string DOMICILIO { get; set; }
        public string LOCALIDAD { get; set; }
        public Nullable<double> PROVINCIA { get; set; }
        public Nullable<double> CODPOS { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<double> COND_IVA { get; set; }
        public Nullable<double> NRO_CUIT { get; set; }
        public Nullable<double> SALDO { get; set; }
        public string OBSERVAC { get; set; }
        public int idProveedor { get; set; }
    }
}
