//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        public int ID_remito { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int ID_pedido { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
