//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigracionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendedoro
    {
        public Nullable<double> N_VENDEDOR { get; set; }
        public string VEN_DESCR { get; set; }
        public string DOMICILIO { get; set; }
        public string LOCALIDAD { get; set; }
        public Nullable<double> PROVINCIA { get; set; }
        public Nullable<double> CODPOS { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string OBSERVAC { get; set; }
        public int idVendedor { get; set; }
    }
}
