//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int ID_compra { get; set; }
        public Nullable<int> ID_proveedor { get; set; }
        public Nullable<System.DateTime> Fecha_compra { get; set; }
        public Nullable<int> Nro_factura { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Nro_operacion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
