//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componente
    {
        public int ID_componente { get; set; }
        public int ID_articulo { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> ID_material { get; set; }
        public Nullable<int> ID_marco { get; set; }
        public string Ciclos { get; set; }
        public string Bocas { get; set; }
        public string Espesor { get; set; }
        public Nullable<int> ID_matriz { get; set; }
        public Nullable<int> ID_cortante { get; set; }
        public string Color { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Cortante Cortante { get; set; }
        public virtual Marco Marco { get; set; }
        public virtual Material Material { get; set; }
        public virtual Matriz Matriz { get; set; }
    }
}
