//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int ID_compra { get; set; }
        public Nullable<int> ID_proveedor { get; set; }
        public Nullable<System.DateTime> Fecha_compra { get; set; }
        public Nullable<int> Nro_factura { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Nro_operacion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
