//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaCteProveedores
    {
        public int id { get; set; }
        public int id_proveedor { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public System.DateTime fecha_movimiento { get; set; }
        public string concepto { get; set; }
        public decimal importe { get; set; }
        public int tipo_movimiento { get; set; }
        public string observaciones { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoMovCtaCte TipoMovCtaCte { get; set; }
    }
}
