//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaCte_Clientes
    {
        public int ID_movimiento { get; set; }
        public Nullable<int> ID_cliente { get; set; }
        public string Razon_social { get; set; }
        public Nullable<int> Saldo { get; set; }
        public Nullable<System.DateTime> Fecha_movimiento { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Importe_movimiento { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
