//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaCteClientes
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public string observacion { get; set; }
        public Nullable<decimal> importe { get; set; }
        public int tipoMovimiento { get; set; }
        public string concepto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoMovCtaCte TipoMovCtaCte { get; set; }
    }
}
