//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_factura
    {
        public int Nro_factura { get; set; }
        public int ID_item { get; set; }
        public int ID_articulo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio_unitario { get; set; }
        public decimal Precio_total { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Encabezado_Factura Encabezado_Factura { get; set; }
    }
}
