//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_factura
    {
        public int Nro_factura { get; set; }
        public int ID_item { get; set; }
        public int ID_articulo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio_unitario { get; set; }
        public decimal Precio_total { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Encabezado_Factura Encabezado_Factura { get; set; }
    }
}
