//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encabezado_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encabezado_Factura()
        {
            this.Detalle_factura = new HashSet<Detalle_factura>();
        }
    
        public int Nro_factura { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int ID_cliente { get; set; }
        public Nullable<int> ID_vendedor { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Tipo_iva_responsable { get; set; }
        public Nullable<decimal> Valor_inscripto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<int> ID_condicon_venta { get; set; }
        public Nullable<int> ID_movimiento { get; set; }
        public Nullable<int> Nro_remito { get; set; }
        public Nullable<int> OrdenCompra { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    
        public virtual Condicion_venta Condicion_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_factura> Detalle_factura { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
