//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Remito = new HashSet<Remito>();
        }
    
        public int ID_pedido { get; set; }
        public int ID_cliente { get; set; }
        public int ID_articulo { get; set; }
        public Nullable<int> cantidad_pedida { get; set; }
        public Nullable<int> cantidad_entregada { get; set; }
        public Nullable<System.DateTime> Fecha_pedido { get; set; }
        public string Orden_compra { get; set; }
        public string Armado { get; set; }
        public Nullable<System.DateTime> Fecha_armado { get; set; }
        public Nullable<System.DateTime> Fecha_entrega { get; set; }
        public Nullable<int> Precio { get; set; }
        public string Observaciones { get; set; }
        public string Impreso { get; set; }
        public Nullable<int> ID_vendedor { get; set; }
        public Nullable<int> Importe_matriz { get; set; }
        public string Tipo_caja { get; set; }
        public string Codigo_articulo_interno_cliente { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remito> Remito { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
