//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        public int ID_presupuesto { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> ID_marco { get; set; }
        public Nullable<int> ID_material { get; set; }
        public Nullable<decimal> Espesor { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Bocas { get; set; }
        public Nullable<decimal> Precio_lista1 { get; set; }
        public Nullable<decimal> Precio_lista2 { get; set; }
        public Nullable<decimal> Precio_lista3 { get; set; }
        public string Observaciones { get; set; }
    }
}
