//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        public int ID_presupuesto { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> ID_marco { get; set; }
        public Nullable<int> ID_material { get; set; }
        public Nullable<decimal> Espesor { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Bocas { get; set; }
        public Nullable<decimal> Precio_lista1 { get; set; }
        public Nullable<decimal> Precio_lista2 { get; set; }
        public Nullable<decimal> Precio_lista3 { get; set; }
        public string Observaciones { get; set; }
    }
}
