//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Compras = new HashSet<Compras>();
            this.CtaCteProveedores = new HashSet<CtaCteProveedores>();
        }
    
        public int ID_proveedor { get; set; }
        public string Razon_social { get; set; }
        public string Contacto { get; set; }
        public string Domicilio { get; set; }
        public string Localidad { get; set; }
        public Nullable<int> Provincia { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Fecha_alta { get; set; }
        public string IVA { get; set; }
        public Nullable<long> CUIT { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtaCteProveedores> CtaCteProveedores { get; set; }
    }
}
