//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Compras = new HashSet<Compras>();
            this.CtaCte_Proveedores = new HashSet<CtaCte_Proveedores>();
        }
    
        public int ID_proveedor { get; set; }
        public string Razon_social { get; set; }
        public string Contacto { get; set; }
        public string Domicilio { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<int> Celular { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Fecha_alta { get; set; }
        public string IVA { get; set; }
        public Nullable<int> CUIT { get; set; }
        public Nullable<int> Saldo { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtaCte_Proveedores> CtaCte_Proveedores { get; set; }
    }
}
