//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blibox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        public int ID_remito { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ID_pedido { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
